[account]
login_id = "hanako-tokyo@autoyours.jp"       # Set your login ID (= email address in the most cases) here.
password = "PASSWORD"                        # Set your password here.
customer_id = "C0012345"                     # Set your own customer ID here.
customer_company_name = "オートヨアーズ"       # Set your company name here.
customer_name = "東京 花子"                   # Set your name (Kanji) here.
customer_email = "hanako-tokyo@autoyours.jp" # Set your email address here.

[setups]
service_id = "S001"          # 東京(S001)
service_menu_id = "S0000063" # セルリアン(S0000063) フクラス(S0000064)
next_monday1 = 1230          # Next Monday
next_tuesday1 = 1200         # Next Tuesday
next_wednesday1 = 1300       # Next Wednesday
next_thursday1 = 0           # Next Thursday
next_friday1 = 0             # Next Friday
next_monday2 = 0             # Monday in two weeks
next_tuesday2 = 1215         # Tuesday in two weeks
next_wednesday2 = 1315       # Wednesday in two weeks
next_thursday2 = 0           # Thursday in two weeks
next_friday2 = 0             # Friday in two weeks
